name: dx_plugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: 4.0.0 #网络请求
  crypto: 3.0.1  #MD5
  get_storage: 2.0.3 #存储--持久化
  flutter_svg: 0.22.0 #svg
  cached_network_image: 3.0.0 #網絡圖片緩存
  flutter_smart_dialog: 3.3.7
  pull_to_refresh: 2.0.0 # 上拉加载下拉刷新
  web_socket_channel: 2.1.0
  tuple: 2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
