name: common
description: A new Flutter package project.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ## ---- common ----
  provider: ^6.1.2
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  flutter_local_notifications: ^18.0.1
  intl: ^0.20.1
  package_info_plus: ^8.1.2
  ## ---- log ----
  logger: ^2.5.0
  go_router: ^14.6.2
  provider: ^6.1.2
  ## ---- network ----
  dio: ^5.7.0
  crypto: ^3.0.6
  shared_preferences: ^2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
